### ISSUE TITLE
Broken rgb_to_hex.py

### ISSUE THREAD

**Issue by AustinWindley** [AustinWindley/MustardIsBetterThanKetchup-Wrong-.com#10]
Description: Every line is broken through incorrect variable assignment and incorrect rgb values.

Steps to Reproduce:

- test with hex_color = rgb_to_hex(255, 127, 0), should return "FF7F00"

Expected Behavior: RGB value inputted into function and correct hex value of color returned

Actual Behavior: RGB value inputted and incorrect hex value returned

Screenshots: No

Additional Information:

- Operating System: Windows
- Browser: Firefox
- Version: test with hex_color = 132.0.1
- Sweatshirt: Colorful
- Hair: Clean
- Emails: Lots of em

Possible Solution: Re-evaluate all number values in file; max functions should go from 0 to 255 each. Format in return statement should be format(r,g,b)

Related Issues: None

Priority: MAXIMUM PRIORITY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Reproducibility: Every single time

Impact: High Impact. Whole file is broken and function will never work as intended until fixed.

**Comment by mwallace37** [comment]
Resolved it.  With my bare hands.  No need to thank.

**Comment by AustinWindley** [comment]
Fixeddddd thanksssssss maryyyyyyy
